name: Deploy to AWS
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: eu-west-2
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: pip3 install -e gale8/requirements.txt
      - run: make -C gale8
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
